// <auto-generated />
namespace FT.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fjernelseafdatoerfraentities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fjernelseafdatoerfraentities));
        
        string IMigrationMetadata.Id
        {
            get { return "201901181505294_Fjernelse af datoer fra entities."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
